### ISSUE TITLE
Collision on client peds

### ISSUE THREAD

**Issue by Ex0r** [esx-framework/instance#19]
Is there a fix for players being invisible but colliding with each other, and opening doors in other clients eyes as they are invisible? I find it weird that you can see doors open and also run into 'invisible' players when they are supposed to be instanced. 

The code for the instance resource shows that it makes other peds invisible, and also sets their entity collision to null for the other player, but you can still run into each other.

**Comment by ArkSeyonet** [comment]
All it can do is make the player invisible. Can't stop the player from existing in that position.
