### ISSUE TITLE
instance manual

### ISSUE THREAD

**Issue by simas727** [esx-framework/instance#22]
hello i need some manual how to use instances in standalone script 
what to trigger or something ? If i want to do private office for boos or something ? 
yes i know i can see other scripts but that didn't say anything to me 
if i want do standalone script i need to know basics of this :) and now this for me is universe if someone can  make basic code to help me understand i would be greatfull thanks :)

**Comment by k3nnyq3** [comment]
Looking into other scripts does say a lot. It told me all I needed to know. All you need is to track down the moment instance starts in another script, and find where it ends. And then you will see instance related stuff there and you can go from there.

**Comment by simas727** [comment]
Hello can u tell me other scripts then esx properties ?

2020-09-10, kt, 04:59 k3nnyq3 <notifications@github.com> rašė:

**Comment by k3nnyq3** [comment]
I used the property one. Try carshops, those usually do the same.
